### ISSUE TITLE
ngnix is complaining about missing conf file

### ISSUE THREAD

**Issue by mascheck55** [DanielWTE/ebay-kleinanzeigen-api#1]
while starting nginx in docker  nginx is complaining about the missing /etc/nginx/conf.d/default.conf. I commented out the rm command in the docker file. now the failure comes in line 7 of nginx.conf ...host not found in upstream "app".
I have absolute no idea what to do. I composed the whole from the directory /home/xxx/ebay-kleinanzeigen-api as proposed.

**Comment by DanielWTE** [comment]
Hey @mascheck55 

This project is not maintained anymore. I've created a new scraper API for various online marketplaces. It's not open source. If you're interested, we can discuss your use case, and I will give you access to the API.
